# Generated by Django 5.0.3 on 2024-03-20 12:49

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('entry', models.TextField()),
                ('created_on', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('articlecategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wiki.articlecategory')),
            ],
        ),
    ]
