# Generated by Django 5.0.2 on 2024-05-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_alter_articlecategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-articlecategory', '-created_on']},
        ),
    ]
